import jsPDF from 'jspdf';
import { MealPlan, GroceryItem, Meal } from '../types';

/**
 * Generate and download a PDF for the meal plan
 */
export const downloadPlanAsPDF = (plan: MealPlan, budget: number, people: number, region: string, preferences: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;
  const margin = 15;
  const lineHeight = 7;
  const sectionSpacing = 10;

  // Helper function to add a new page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }
  };

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('7-Day Meal Plan & Grocery List', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += lineHeight * 2;

  // Plan details
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Budget: ₹${budget}`, margin, yPosition);
  yPosition += lineHeight;
  doc.text(`People: ${people}`, margin, yPosition);
  yPosition += lineHeight;
  doc.text(`Region: ${region || 'General Indian'}`, margin, yPosition);
  yPosition += lineHeight;
  doc.text(`Preferences: ${preferences || 'None'}`, margin, yPosition);
  yPosition += sectionSpacing * 2;

  // Meal Plan Section
  checkPageBreak(30);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Meal Plan', margin, yPosition);
  yPosition += lineHeight * 1.5;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  if (Array.isArray(plan.mealPlan)) {
    plan.mealPlan.forEach((day: Meal) => {
      checkPageBreak(25);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(day.day, margin, yPosition);
      yPosition += lineHeight * 1.2;
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Breakfast: ${day.breakfast}`, margin + 5, yPosition);
      yPosition += lineHeight;
      doc.text(`Lunch: ${day.lunch}`, margin + 5, yPosition);
      yPosition += lineHeight;
      doc.text(`Dinner: ${day.dinner}`, margin + 5, yPosition);
      yPosition += sectionSpacing;
    });
  }

  // Grocery List Section
  checkPageBreak(30);
  yPosition += sectionSpacing;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Grocery List', margin, yPosition);
  yPosition += lineHeight * 1.5;

  // Group grocery items by category
  const groupedList = (plan.groceryList || []).reduce((acc: Record<string, GroceryItem[]>, item) => {
    const category = item.category || 'Other';
    if (!acc[category]) {
      acc[category] = [];
    }
    acc[category].push(item);
    return acc;
  }, {} as Record<string, GroceryItem[]>);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  Object.entries(groupedList).forEach(([category, items]) => {
    checkPageBreak(20);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(category, margin, yPosition);
    yPosition += lineHeight * 1.2;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    items.forEach((item) => {
      checkPageBreak(7);
      doc.text(`• ${item.item} (${item.quantity})`, margin + 5, yPosition);
      yPosition += lineHeight;
    });
    yPosition += sectionSpacing / 2;
  });

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text(`Generated by FinAI - Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, pageHeight - 5, { align: 'center' });
  }

  // Generate filename
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `meal-plan-${timestamp}.pdf`;
  
  doc.save(filename);
};

/**
 * Download an image
 */
export const downloadImage = (imageUrl: string, filename: string = 'meal-plan-image.png') => {
  const link = document.createElement('a');
  link.href = imageUrl;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

/**
 * Download a video
 */
export const downloadVideo = (videoUrl: string, filename: string = 'meal-plan-video.mp4') => {
  const link = document.createElement('a');
  link.href = videoUrl;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};




